name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        npm install
        npm install -g playwright
        npx playwright install --with-deps

    - name: Run TestNG tests with debug logging
      run: mvn clean test -X

    - name: Generate Allure report
      run: |
        # Install Allure commandline tool
        wget https://github.com/allure-framework/allure2/releases/download/2.22.3/allure-2.22.3.tgz
        tar -zxvf allure-2.22.3.tgz
        sudo mv allure-2.22.3 /usr/local/bin/allure
        sudo ln -s /usr/local/bin/allure/bin/allure /usr/bin/allure

        # Generate the report
        allure generate target/allure-results --clean -o target/allure-report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/allure-report
        retention-days: 30
