name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        npm install
        npm install -g playwright
        npx playwright install --with-deps

    - name: Run TestNG tests
      run: mvn clean test

    - name: Generate Allure report
      run: mvn allure:report

    - name: Serve Allure report
      run: mvn allure:serve

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/site/allure-maven/index.html
        retention-days: 30
