name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enable manual workflow trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Node.js and Playwright dependencies
      run: |
        npm install
        npm install -g playwright
        npx playwright install --with-deps

    - name: Run tests with debug logging
      run: |
        mvn clean test -X || true
      env:
        FILE_BASE_DIR: ${{ github.workspace }} # Ensure proper pathing for file handling

    - name: Upload Surefire Reports
      if: always() # Ensure this step runs even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target/surefire-reports

    - name: Generate Allure Report
      run: |
        mvn allure:report

    - name: Serve Allure Report
      run: |
        mvn allure:serve

    - name: Upload Allure Report
      if: always() # Ensure this step runs even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Debug Allure Results (Optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results

    - name: Notify Build Status
      if: failure() # Runs only if the previous steps failed
      run: echo "Build failed! Please check the uploaded reports for more details."
