name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Specify the Java distribution

    - name: Install dependencies
      run: |
        npm install
        npm install -g playwright
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Run TestNG tests
      run: mvn test

    - name: Generate Playwright report
      run: npx playwright show-report

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload TestNG report
      uses: actions/upload-artifact@v4
      with:
        name: testng-report
        path: target/surefire-reports/
        retention-days: 30
