jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        npm install
        npm install -g playwright
        npx playwright install --with-deps

    - name: Run tests with debug logging
      run: mvn clean test -X || true

    - name: Upload Surefire Reports
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target/surefire-reports

    - name: Generate Allure Report
      run: |
        allure generate target/allure-results --clean -o target/allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/allure-report
